apiVersion: v1
kind: Service
metadata:
  labels:
    name: valheim-service
  name: valheim-service
spec:
  type: LoadBalancer
  ports:
    - port: 2456
      targetPort: 2456
      protocol: UDP
      name: game1
    - port: 2457
      targetPort: 2457
      protocol: UDP
      name: game2
    - port: 2458
      targetPort: 2458
      protocol: UDP
      name: game3
  selector:
    name: valheim-server
